### ISSUE TITLE
Books Not Added

### ISSUE THREAD

**Issue by VIJAYWHAT** [techatpark/gurukulam#125]
**Describe the bug**
Books are not added in the content of Gurukulams 

**To Identify**
Steps to Identify the Bug:
1. Go to [This Page](https://gurukulams.com/books/csebooks/c-programming/foundation/what-is-c/)
2. Click on Book icon
3. No any books are displayed here

**Expected behavior**
Books want to display on clicking the Book icon

**Actual behavior**
No any books are displayed on clicking the Book icon

**Screenshot**
<img width="605" alt="Screenshot 2023-12-04 162314" src="https://github.com/techatpark/gurukulam/assets/89501520/c8f29025-1476-47f8-a387-2db77d1af45b">

**Comment by rmhari** [comment]
@VIJAYWHAT  Check https://gurukulams.com/books/tnebooks/11th-botany/plant-growth-and-development/characteristics-of-growth/
