### ISSUE TITLE
Connection tag Not Display

### ISSUE THREAD

**Issue by VIJAYWHAT** [techatpark/gurukulam#126]
**Describe the bug**
Connection tag in not showing after the refresh or go and back from other page

**To Reproduce**
1. Go to [This Page](https://gurukulams.com/books/csebooks/c-programming/foundation/what-is-c/)
2. Create any two notes
3. Now use connection tool and connect the Notes
4. Now go to other page and comeback or refresh the page that connection tag was not showing
5. Logout and Login the page, all notes are showing but connection tag are not showing

**Expected behavior**
Connection tag show always if go any page or logout and login

**Actual behavior**
Connection tags are not showing after the refresh

**Screenshots**
Before Refresh
<img width="942" alt="Screenshot 2023-12-04 163258" src="https://github.com/techatpark/gurukulam/assets/89501520/85fcc912-d642-43f0-9087-996baffb99a4">

After Refresh
<img width="560" alt="Screenshot 2023-12-04 163349" src="https://github.com/techatpark/gurukulam/assets/89501520/aa42251c-d8b9-4ac9-b38e-bbb5e6268b66">

**Comment by rmhari** [comment]
Done
