### ISSUE TITLE
Class not Started 

### ISSUE THREAD

**Issue by VIJAYWHAT** [techatpark/gurukulam#127]
**Describe the bug**
Class not started before 10mins or at the time

**To Reproduce**
1. Go to [This Page](https://gurukulams.com/books/csebooks/c-programming/foundation/what-is-c/)
2. Click on Class Icon
3. Create one Class
4. Set the starting time within 10mins
5. Give the Meeting URL
6. try to start the class 

**Expected behavior**
Class want to at the time

**Actual Behavior**
Class Was not started, it showing (Event not available)

**Screenshots**
<img width="954" alt="image" src="https://github.com/techatpark/gurukulam/assets/89501520/f65b5081-6a29-4853-b75e-9ec290e0167d">

**Comment by rmhari** [comment]
Done
