### ISSUE TITLE
Image Zoom is working only for English

### ISSUE THREAD

**Issue by rmhari** [techatpark/gurukulam#128]
**Describe the bug**
Image Zoom is working only for English

**To Reproduce**
1. Go to '[Any Page that contains image](https://gurukulams.com/books/tnebooks/11th-botany/plant-growth-and-development/characteristics-of-growth/)'
2. Click on Login
3. Click on Any Image
4. See the image opening in full screen. Press escape.
5. Change Language to Tamil
6. Click on Any Image

**Expected behavior**
We should ee the image opening in full screen. 

**Actual behavior**
Nothing

**Comment by venkateshwaranL** [comment]
Its working
