### ISSUE TITLE
slide text in dark theme

### ISSUE THREAD

**Issue by VIJAYWHAT** [techatpark/gurukulam#134]
### Description

slides text are showing black in dark theme so the text is not showing clearly

### Steps To Reproduce

1. Go to [Gurukulam](https://gurukulams.com/courses/books/tnebooks/11th-botany/plant-growth-and-development/characteristics-of-growth/)
2.Slide text show in black color

### Expected behavior
text show in white color

### Actual behavior
text show in black color

### Screen shot
<img width="944" alt="image" src="https://github.com/techatpark/gurukulam/assets/89501520/1257b8ec-1fa3-4d04-8e09-69ec0692c339">

**Comment by rmhari** [comment]
Done.
